/*
 * This source file was generated by the Gradle 'init' task
 */
package hello;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasGreeting() {
        App a = new App();
        assertNotNull(a.getGreeting(), "App must have a greeting");
    }

    @Test void greetingIsHelloWorld() {
        App a = new App();
        assertEquals("Hello World!", a.getGreeting());
    }
}
