/*
 * This source file was generated by the Gradle 'init' task
 */
package hello;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        App a = new App();
        String greeting = a.getGreeting();
        System.out.println(greeting);
    }
}
